"""add preference audit columns to feed_impressions

Revision ID: 635ef41389c3
Revises: ba782991717b
Create Date: 2026-07-07 12:01:05.427418

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '635ef41389c3'
down_revision: str | None = 'ba782991717b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_impressions', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('feed_impressions', sa.Column('preference_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_impressions', 'preference_multiplier')
    op.drop_column('feed_impressions', 'preferences')
    # ### end Alembic commands ###
