"""initial schema

Revision ID: 99272754b1c1
Revises: 
Create Date: 2026-07-07 05:51:32.287040

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '99272754b1c1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-added, ahead of the autogenerated body: the tables below declare CITEXT and
    # Vector(384) columns, so the extensions must exist first. db/init/01-extensions.sql
    # only runs via the Compose image's docker-entrypoint-initdb.d hook, which no managed
    # Postgres (Fly MPG included) provides. IF NOT EXISTS makes this a no-op on any DB
    # already at head, and makes the schema self-bootstrapping everywhere else.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_ledger',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('reactions_used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day', name=op.f('pk_budget_ledger'))
    )
    op.create_table('topic_centroids',
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('topic', name=op.f('pk_topic_centroids'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('handle', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_persona', sa.Boolean(), nullable=False),
    sa.Column('archetype', sa.Enum('founder', 'journalist', 'meme', 'trader', 'politician', 'engineer', 'artist', 'other', name='archetype'), nullable=True),
    sa.Column('persona_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('handle', name=op.f('uq_users_handle'))
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('followee_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], name=op.f('fk_follows_followee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id', name=op.f('pk_follows'))
    )
    op.create_index('ix_follows_followee_id', 'follows', ['followee_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('post', 'reply', 'quote', name='post_kind'), nullable=False),
    sa.Column('in_reply_to_id', sa.Uuid(), nullable=True),
    sa.Column('quoted_post_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['posts.id'], name=op.f('fk_posts_conversation_id_posts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['in_reply_to_id'], ['posts.id'], name=op.f('fk_posts_in_reply_to_id_posts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quoted_post_id'], ['posts.id'], name=op.f('fk_posts_quoted_post_id_posts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index('ix_posts_author_id_created_at', 'posts', ['author_id', 'created_at'], unique=False, postgresql_include=['id'])
    op.create_index('ix_posts_conversation_id', 'posts', ['conversation_id'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_in_reply_to_id', 'posts', ['in_reply_to_id'], unique=False)
    op.create_index('ix_posts_quoted_post_id', 'posts', ['quoted_post_id'], unique=False)
    op.create_index('ix_posts_topics', 'posts', ['topics'], unique=False, postgresql_using='gin')
    op.create_table('user_embeddings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_embeddings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_embeddings'))
    )
    op.create_table('user_relationships',
    sa.Column('source_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('block', 'mute', name='relationship_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], name=op.f('fk_user_relationships_source_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_user_relationships_target_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_user_id', 'target_user_id', 'kind', name=op.f('pk_user_relationships'))
    )
    op.create_table('engagements',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('like', 'reply', 'repost', 'quote', 'click', 'dwell', 'report', name='engagement_kind'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_engagements_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_engagements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engagements'))
    )
    op.create_index('ix_engagements_post_id_created_at', 'engagements', ['post_id', 'created_at'], unique=False)
    op.create_index('ix_engagements_user_id_created_at', 'engagements', ['user_id', 'created_at'], unique=False)
    op.create_table('feed_impressions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('action_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('weight_vector', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('mmr_penalty', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_feed_impressions_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feed_impressions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_impressions'))
    )
    op.create_index('ix_feed_impressions_user_id_request_id', 'feed_impressions', ['user_id', 'request_id'], unique=False)
    op.create_table('post_embeddings',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_embeddings_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', name=op.f('pk_post_embeddings'))
    )
    op.create_index('ix_post_embeddings_embedding_hnsw', 'post_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('post_velocity',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('window', sa.Enum('h1', 'h6', 'h24', name='velocity_window'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_velocity_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'window', name=op.f('pk_post_velocity'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_velocity')
    op.drop_index('ix_post_embeddings_embedding_hnsw', table_name='post_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('post_embeddings')
    op.drop_index('ix_feed_impressions_user_id_request_id', table_name='feed_impressions')
    op.drop_table('feed_impressions')
    op.drop_index('ix_engagements_user_id_created_at', table_name='engagements')
    op.drop_index('ix_engagements_post_id_created_at', table_name='engagements')
    op.drop_table('engagements')
    op.drop_table('user_relationships')
    op.drop_table('user_embeddings')
    op.drop_index('ix_posts_topics', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_quoted_post_id', table_name='posts')
    op.drop_index('ix_posts_in_reply_to_id', table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_conversation_id', table_name='posts')
    op.drop_index('ix_posts_author_id_created_at', table_name='posts', postgresql_include=['id'])
    op.drop_table('posts')
    op.drop_index('ix_follows_followee_id', table_name='follows')
    op.drop_table('follows')
    op.drop_table('users')
    op.drop_table('topic_centroids')
    op.drop_table('budget_ledger')
    # ### end Alembic commands ###
