"""add scoring_model_version to feed_impressions

Revision ID: ba782991717b
Revises: 99272754b1c1
Create Date: 2026-07-07 09:12:04.253989

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ba782991717b'
down_revision: str | None = '99272754b1c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_impressions', sa.Column('scoring_model_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_impressions', 'scoring_model_version')
    # ### end Alembic commands ###
